import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
      className="bg-linear-to-br from-amber-50 via-orange-50 to-orange-400 bg-fixed amp-mask">
        {children}
      </body>
    </html>
  );
}
